version: "3.9"
services:
  nopcommerce_web:
    build: .
    container_name: nopcommerce
    ports:
      - 80:80
  nopcommerce_database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "qualitythought@123"
    volumes:
      - type: volume
        source: nopcommerce_data
        target: /var/lib/mysql

volumes:
  nopcommerce_data:


