---
version: "3.8"
services:
  gameoflife:
    build:
      context: gameoflife/
    ports:
      - "32765:8080"
    volumes:
      - tmp-volume:/tmp
  spring-petclinic:
    build:
      context: spring-petclinic/
    ports:
      - "32766:8080"
    volumes:
      - tmp-volume:/tmp
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - tmp-volume:/tmp
volumes:
  mysql-volume:
  tmp-volume: